version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
  build:
    commands:
      - npm install -g npm@latest
      - npm install
      - npm run build

artifacts:
  files:
    - public/**/*
    - styles/**/*
    - utils/**/*
    - .ebextensions/**/*
    - .next/**/*
    - prisma/**/*
    - package-lock.json
    - package.json

cache:
  paths:
    - node_modules/**/*
